/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package deckbldr.ui;
import deckbldr.domain.Card;
import deckbldr.logic.SearchLogic;
import java.util.*;
import javax.swing.*;

/**
 *
 * @author abuja915
 */
public class CardSearchPanel extends javax.swing.JPanel {
    private String cardNameEntry;
    private int powerEntry;
    private int toughnessEntry;
    private String costEntry;
    private ArrayList<String> colors= new ArrayList<String>();
    private ArrayList<String> types= new ArrayList<String>();
    private ArrayList<Card> results=new ArrayList<Card>();
    private DefaultListModel model= new DefaultListModel();
    /**
     * Creates new form CardSearchPanel
     */
    public CardSearchPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CardSearchBarTextField = new javax.swing.JTextField();
        CardSearchButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        ToughnessTextField = new javax.swing.JTextField();
        PowerTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        CardSearchColorList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        CardSearchTypesList = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        costCardTextfield = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        ResultsCardSearchJlist = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();

        CardSearchBarTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CardSearchBarTextFieldActionPerformed(evt);
            }
        });

        CardSearchButton.setText("Search");
        CardSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CardSearchButtonActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Search Filters"));

        ToughnessTextField.setText("0");
        ToughnessTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToughnessTextFieldActionPerformed(evt);
            }
        });

        PowerTextField.setText("0");
        PowerTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PowerTextFieldActionPerformed(evt);
            }
        });

        CardSearchColorList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "White", "Black", "Red", "Blue", "Green" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        CardSearchColorList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                CardSearchColorListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(CardSearchColorList);

        CardSearchTypesList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "artifact", "creature", "enchantment", "instant", "land", "phenomenon", "plane", "planeswalker", "scheme", "sorcery", "tribal", "vanguard" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        CardSearchTypesList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                CardSearchTypesListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(CardSearchTypesList);

        jLabel2.setText("Cost");

        jLabel3.setText("Power");

        jLabel4.setText("Toughness");

        jLabel5.setText("Type");

        jLabel6.setText("Color");

        jLabel7.setText("Results");

        costCardTextfield.setText("{?}{?}");
        costCardTextfield.setToolTipText("");
        costCardTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costCardTextfieldActionPerformed(evt);
            }
        });

        ResultsCardSearchJlist.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jScrollPane4.setViewportView(ResultsCardSearchJlist);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane4)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(costCardTextfield)
                                    .addComponent(PowerTextField)
                                    .addComponent(ToughnessTextField))))
                        .addContainerGap(20, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(costCardTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PowerTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ToughnessTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(8, 8, 8)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setText("Card Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CardSearchBarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(CardSearchButton)
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CardSearchBarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CardSearchButton)
                    .addComponent(jLabel1))
                .addGap(35, 35, 35)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CardSearchBarTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CardSearchBarTextFieldActionPerformed
       
      
    }//GEN-LAST:event_CardSearchBarTextFieldActionPerformed

    private void CardSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CardSearchButtonActionPerformed
        SearchLogic search= new SearchLogic();
        
        cardNameEntry=null;
        powerEntry=0;
        toughnessEntry=0;
        costEntry=null;
        colors.clear();
        types.clear();
        
        
        
        
          CardPanelSearcher();
          
          
          if(colors.isEmpty()){
            if(types.isEmpty()){
                System.out.println("Colors and types are empty");
                if(cardNameEntry==null && powerEntry==0 && toughnessEntry==0 && costEntry==null){
                    results=null;
                }
                else{
                results=search.runDBSearch(cardNameEntry, costEntry, toughnessEntry,powerEntry, null, null);
                }
             } 
                
            else{
                System.out.println("Colors is empty");
                results=search.runDBSearch(cardNameEntry, costEntry, toughnessEntry,powerEntry, null, types);
            } 
           
          }
          else if(types.isEmpty()){
              System.out.println("types is empty");
              results=search.runDBSearch(cardNameEntry, costEntry, toughnessEntry,powerEntry, colors, null);
          }
          else{
              System.out.println("Colors and types are NOT empty");
          results=search.runDBSearch(cardNameEntry, costEntry, toughnessEntry,powerEntry, colors, types);
          }
         // System.out.println("RESULTS SIZE: "+results.size());
          
          model.removeAllElements();
          if(results==null){
              model.addElement("Search found nothing.");
          }
          else{
          for(Card res: results){
               
              model.addElement(res.getName());
          }
          }
        ResultsCardSearchJlist.setModel(model);
        
       
    
    }//GEN-LAST:event_CardSearchButtonActionPerformed

    private void CardSearchTypesListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_CardSearchTypesListValueChanged
        
    }//GEN-LAST:event_CardSearchTypesListValueChanged

    private void CardSearchColorListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_CardSearchColorListValueChanged
        
    }//GEN-LAST:event_CardSearchColorListValueChanged

    private void PowerTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PowerTextFieldActionPerformed

    }//GEN-LAST:event_PowerTextFieldActionPerformed

    private void ToughnessTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToughnessTextFieldActionPerformed

    }//GEN-LAST:event_ToughnessTextFieldActionPerformed

    private void costCardTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costCardTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_costCardTextfieldActionPerformed

    public void CardPanelSearcher(){
        String name=CardSearchBarTextField.getText();
            if(name.equals("")){
                name=null;
            }
            cardNameEntry=name;
        
        String cost=costCardTextfield.getText();
            if(cost.equals("{?}{?}")){
                cost=null;
            }
            costEntry=cost;
            
        String pe=PowerTextField.getText();
            try{
               int power= Integer.parseInt(pe);
               powerEntry=power;
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, "Please enter a valid number");
                powerEntry=0;
            }
            
        String te= ToughnessTextField.getText();
            try{
               int toughness=Integer.parseInt(te);
               toughnessEntry=toughness;
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, "Please enter a valid number");
                toughnessEntry=0;
            }
           
        //String cmc=CMCDropDown.getSelectedItem().toString();
        
        List sl= CardSearchTypesList.getSelectedValuesList();
        for(int i=0;i<sl.size();i++){
           String temp=sl.get(i).toString();
           types.add(temp);
           }
        
        List sl1= CardSearchColorList.getSelectedValuesList();
        for(int j=0;j<sl1.size();j++){
           String temp1=sl1.get(j).toString();
           colors.add(temp1);
           }   
        
        
        System.out.println(cardNameEntry+" "+toughnessEntry+" "+powerEntry+" "+costEntry+" "+colors+" "+types);
       // System.out.println(colors.toString());
        
    }
    
    public Card addCardSelect(){
       Object tempCard= ResultsCardSearchJlist.getSelectedValue();
       String tempCardName=tempCard.toString();
       
       Card choosen= new Card();
       for(int g=0;g<results.size();g++){
           
           if(tempCard.equals(results.get(g).getName())){
               choosen=results.get(g);
               System.out.println(choosen.getMultiverseID());
               return choosen;
           }
           
       }
        return null;
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CardSearchBarTextField;
    private javax.swing.JButton CardSearchButton;
    private javax.swing.JList CardSearchColorList;
    private javax.swing.JList CardSearchTypesList;
    private javax.swing.JTextField PowerTextField;
    private javax.swing.JList ResultsCardSearchJlist;
    private javax.swing.JTextField ToughnessTextField;
    private javax.swing.JTextField costCardTextfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
